language: java
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: /home/travis/.m2/repository/sample/jsf-flow-portlet/0.0.3/jsf-flow-portlet-0.0.3.war
  skip_cleanup: true
  on:
    tags: true
